from freezegun import freeze_time

from odoo.exceptions import ValidationError
from odoo.tests import tagged

from odoo.addons.sale_subscription.tests.common_sale_subscription import TestSubscriptionCommon


@tagged('post_install', '-at_install')
class TestSubscriptionQuotas(TestSubscriptionCommon):

    def _product_lines(self, invoice):
        return invoice.invoice_line_ids.filtered('product_id')

    def _confirm_subscription(self, **vals):
        sub = self.subscription
        sub.write(vals)
        sub.action_confirm()
        return sub

    def _assert_legend(self, invoice, legend):
        lines = self._product_lines(invoice)
        self.assertTrue(lines)
        for line in lines:
            self.assertTrue(line.name.endswith(f"\n{legend}"), line.name)
            self.assertEqual(line.name.count(legend), 1)

    def _assert_no_legend(self, invoice):
        for line in self._product_lines(invoice):
            self.assertNotIn("installment", line.name.lower())
            self.assertFalse(line.subscription_quota)

    # Defaults and view

    def test_default_values(self):
        """Installment control is opt-in: new orders have no installments set."""
        sub = self.subscription
        self.assertEqual(sub.next_quota, 1)
        self.assertEqual(sub.max_quotas, 0)
        self.assertEqual(sub.quota_legend, "Billed installment %d of %d")

    def test_form_view_shows_quota_fields(self):
        """The subscription form exposes the three quota fields."""
        arch = self.env['sale.order'].get_view(
            view_id=self.env.ref('sale_subscription.sale_subscription_order_view_form').id,
            view_type='form',
        )['arch']
        for field_name in ('next_quota', 'max_quotas', 'quota_legend'):
            self.assertIn(f'name="{field_name}"', arch)

    def test_disabled_by_default(self):
        """Without a maximum number of installments nothing changes, nor closes."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription()
            invoice = sub._create_invoices()
            invoice.action_post()
        self._assert_no_legend(invoice)
        self.assertEqual(sub.next_quota, 1)
        self.assertEqual(sub.subscription_state, '3_progress')

    # Legend and counter

    def test_counter_moves_on_post_not_on_creation(self):
        """The legend is added on creation, the counter only moves on confirmation."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(max_quotas=12)
            invoice = sub._create_invoices()
            self._assert_legend(invoice, "Billed installment 1 of 12")
            self.assertEqual(set(self._product_lines(invoice).mapped('subscription_quota')), {1})
            self.assertEqual(sub.next_quota, 1)

            invoice.action_post()
        self.assertEqual(sub.next_quota, 2)
        self.assertEqual(sub.subscription_state, '3_progress')

    def test_deleted_draft_does_not_consume_installment(self):
        """A draft invoice deleted before confirmation (e.g. failed automatic
        payment) does not skip an installment."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(max_quotas=12)
            sub._create_invoices().unlink()
            self.assertEqual(sub.next_quota, 1)

            invoice = sub._create_invoices()
        self._assert_legend(invoice, "Billed installment 1 of 12")

    def test_cancelled_draft_does_not_consume_installment(self):
        """Cancelling a draft invoice leaves the counter untouched."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(max_quotas=12)
            invoice = sub._create_invoices()
            invoice.button_cancel()
        self.assertEqual(sub.next_quota, 1)

    def test_repost_does_not_skip_installment(self):
        """Resetting to draft and confirming again keeps the same installment."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(max_quotas=12)
            invoice = sub._create_invoices()
            invoice.action_post()
            invoice.button_draft()
            invoice.action_post()
        self.assertEqual(sub.next_quota, 2)

    def test_consecutive_quotas_through_cron(self):
        """Each recurring invoice generated by the cron carries the next installment."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(max_quotas=3, quota_legend="Cuota %d de %d")
            first_invoice = sub._create_invoices()
            first_invoice.action_post()
        self._assert_legend(first_invoice, "Cuota 1 de 3")
        self.assertEqual(sub.next_quota, 2)

        with freeze_time('2026-02-01'):
            second_invoice = sub._create_recurring_invoice()
        self.assertEqual(len(second_invoice), 1)
        self.assertEqual(second_invoice.state, 'posted')
        self._assert_legend(second_invoice, "Cuota 2 de 3")
        self.assertEqual(sub.next_quota, 3)
        self.assertEqual(sub.subscription_state, '3_progress')

    def test_custom_starting_quota(self):
        """A subscription can start mid-plan (e.g. migrated contracts)."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(next_quota=5, max_quotas=10)
            invoice = sub._create_invoices()
            invoice.action_post()
        self._assert_legend(invoice, "Billed installment 5 of 10")
        self.assertEqual(sub.next_quota, 6)

    # Automatic closing

    def test_closes_after_last_installment_through_cron(self):
        """Confirming the last installment closes the subscription."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(max_quotas=2)
            sub._create_invoices().action_post()
        self.assertEqual(sub.subscription_state, '3_progress')

        with freeze_time('2026-02-01'):
            last_invoice = sub._create_recurring_invoice()
        self._assert_legend(last_invoice, "Billed installment 2 of 2")
        self.assertEqual(sub.next_quota, 3)
        self.assertEqual(sub.subscription_state, '6_churn')
        self.assertEqual(sub.close_reason_id, self.env.ref('sale_subscription.close_reason_end_of_contract'))
        self.assertTrue(any(
            "closed automatically" in (body or '') for body in sub.message_ids.mapped('body')
        ))

    def test_closes_single_installment_on_manual_post(self):
        """A one-installment subscription closes as soon as its invoice is confirmed."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(max_quotas=1)
            invoice = sub._create_invoices()
            self.assertEqual(sub.subscription_state, '3_progress')
            invoice.action_post()
        self.assertEqual(sub.subscription_state, '6_churn')

    def test_no_legend_once_plan_is_finished(self):
        """A subscription whose installments are all invoiced (e.g. reopened by
        hand) gets no legend nor counter change."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(next_quota=4, max_quotas=3)
            invoice = sub._create_invoices()
            invoice.action_post()
        self._assert_no_legend(invoice)
        self.assertEqual(sub.next_quota, 4)
        self.assertEqual(sub.subscription_state, '3_progress')

    # Validations

    def test_negative_max_quotas_rejected(self):
        with self.assertRaises(ValidationError):
            self.subscription.max_quotas = -1

    def test_next_quota_below_one_rejected(self):
        with self.assertRaises(ValidationError):
            self.subscription.write({'max_quotas': 12, 'next_quota': 0})

    def test_next_quota_above_max_rejected(self):
        with self.assertRaises(ValidationError):
            self.subscription.write({'max_quotas': 12, 'next_quota': 14})
        self.subscription.write({'max_quotas': 12, 'next_quota': 13})

    def test_invalid_legends_rejected(self):
        for legend in ("Cuota %d", "Cuota %s de %d", "Cuota %d de %d de %d", "Cuota %d de %d %", False):
            with self.subTest(legend=legend), self.assertRaises(ValidationError):
                self.subscription.write({'max_quotas': 12, 'quota_legend': legend})

    def test_invalid_legend_allowed_when_disabled(self):
        """Validations only apply when installment control is enabled."""
        self.subscription.write({'max_quotas': 0, 'quota_legend': "Cuota %d", 'next_quota': 0})

    def test_stored_invalid_legend_does_not_break_invoicing(self):
        """Data saved before the validation existed is skipped, not swallowed
        by a bare except."""
        sub = self._confirm_subscription(max_quotas=12)
        self.env.cr.execute("UPDATE sale_order SET quota_legend = %s WHERE id = %s", ("Cuota %s", sub.id))
        sub.invalidate_recordset(['quota_legend'])
        with freeze_time('2026-01-01'):
            invoice = sub._create_invoices()
            invoice.action_post()
        self.assertNotIn("Cuota", " ".join(self._product_lines(invoice).mapped('name')))
        self.assertEqual(sub.next_quota, 1)

    # Non-subscription orders

    def test_regular_sale_order_is_untouched(self):
        """Non-recurring sale orders never get a legend nor a counter change."""
        product = self.env['product.product'].create({
            'name': 'One-shot service',
            'type': 'service',
            'invoice_policy': 'order',
            'list_price': 10,
        })
        order = self.env['sale.order'].create({
            'partner_id': self.partner.id,
            'max_quotas': 12,
            'order_line': [(0, 0, {'product_id': product.id, 'product_uom_qty': 1})],
        })
        order.action_confirm()
        self.assertFalse(order.is_subscription)
        invoice = order._create_invoices()
        invoice.action_post()
        self._assert_no_legend(invoice)
        self.assertEqual(order.next_quota, 1)
