from freezegun import freeze_time

from odoo.tests import tagged

from odoo.addons.sale_subscription.tests.common_sale_subscription import TestSubscriptionCommon


@tagged('post_install', '-at_install')
class TestSubscriptionQuotas(TestSubscriptionCommon):

    def _product_lines(self, invoice):
        return invoice.invoice_line_ids.filtered('product_id')

    def _confirm_subscription(self, **vals):
        sub = self.subscription
        sub.write(vals)
        sub.action_confirm()
        return sub

    def test_default_values(self):
        """New orders start at quota 1 of 1 with the default legend."""
        sub = self.subscription
        self.assertEqual(sub.next_quota, 1)
        self.assertEqual(sub.max_quotas, 1)
        self.assertEqual(sub.quota_legend, "Cuota facturada %d de %d")

    def test_form_view_shows_quota_fields(self):
        """The subscription form exposes the three quota fields."""
        arch = self.env['sale.order'].get_view(
            view_id=self.env.ref('sale_subscription.sale_subscription_order_view_form').id,
            view_type='form',
        )['arch']
        for field_name in ('next_quota', 'max_quotas', 'quota_legend'):
            self.assertIn(f'name="{field_name}"', arch)

    def test_legend_and_increment_on_manual_invoice(self):
        """Manual invoicing appends the legend to every product line and bumps next_quota."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(next_quota=1, max_quotas=12)
            invoice = sub._create_invoices()

        lines = self._product_lines(invoice)
        self.assertTrue(lines)
        for line in lines:
            self.assertTrue(line.name.endswith("\nCuota facturada 1 de 12"))
            self.assertEqual(line.name.count("Cuota facturada"), 1)
        self.assertEqual(sub.next_quota, 2)

    def test_consecutive_quotas_through_cron(self):
        """Each recurring invoice generated by the cron carries the next quota number."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(next_quota=1, max_quotas=3, quota_legend="Cuota %d de %d")
            first_invoice = sub._create_invoices()
            first_invoice.action_post()
        self.assertIn("Cuota 1 de 3", self._product_lines(first_invoice)[0].name)
        self.assertEqual(sub.next_quota, 2)

        with freeze_time('2026-02-01'):
            second_invoice = sub._create_recurring_invoice()
        self.assertEqual(len(second_invoice), 1)
        for line in self._product_lines(second_invoice):
            self.assertTrue(line.name.endswith("\nCuota 2 de 3"))
        self.assertEqual(sub.next_quota, 3)

    def test_custom_starting_quota(self):
        """A subscription can start mid-plan (e.g. migrated contracts)."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(next_quota=5, max_quotas=10)
            invoice = sub._create_invoices()
        for line in self._product_lines(invoice):
            self.assertTrue(line.name.endswith("\nCuota facturada 5 de 10"))
        self.assertEqual(sub.next_quota, 6)

    def test_invalid_legend_is_ignored(self):
        """A legend without two %d placeholders leaves lines and counter untouched."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(max_quotas=12, quota_legend="Cuota %d")
            invoice = sub._create_invoices()
        for line in self._product_lines(invoice):
            self.assertNotIn("Cuota", line.name)
        self.assertEqual(sub.next_quota, 1)

    def test_empty_quota_values_are_ignored(self):
        """Zero max_quotas disables the feature for that subscription."""
        with freeze_time('2026-01-01'):
            sub = self._confirm_subscription(max_quotas=0)
            invoice = sub._create_invoices()
        for line in self._product_lines(invoice):
            self.assertNotIn("Cuota facturada", line.name)
        self.assertEqual(sub.next_quota, 1)

    def test_regular_sale_order_is_untouched(self):
        """Non-recurring sale orders never get a legend nor a counter bump."""
        product = self.env['product.product'].create({
            'name': 'One-shot service',
            'type': 'service',
            'invoice_policy': 'order',
            'list_price': 10,
        })
        order = self.env['sale.order'].create({
            'partner_id': self.partner.id,
            'max_quotas': 12,
            'order_line': [(0, 0, {'product_id': product.id, 'product_uom_qty': 1})],
        })
        order.action_confirm()
        self.assertFalse(order.is_subscription)
        invoice = order._create_invoices()
        self.assertNotIn("Cuota facturada", self._product_lines(invoice).name)
        self.assertEqual(order.next_quota, 1)
